### ISSUE TITLE
link do modelo pre treinado offline

### ISSUE THREAD

**Issue by regisroots** [JpThomaz/ALPR-Python-Brazill#1]
Olá tudo bem? poderia realizar o upload o modelo pre treinado por favor? obrigado! o projeto ficou muito bom!

**Comment by JpThomaz** [comment]
Obrigado pelo comentário. Tive que remover o modelo por conta de armazenamento do Drive mas vou subir novamente.

**Comment by regisroots** [comment]
Muito obrigado Thomaz, aguardando.

**Comment by JpThomaz** [comment]
Subi como release aqui no git, você pode baixar nesse link. https://github.com/JpThomaz/ALPR-Python-Brazill/releases/download/model/lapi.weights

**Comment by regisroots** [comment]
Baixei, obrigado.
